### PR TITLE
fix initial VC build

### PR DESCRIPTION
**Pull request by bravit**
Files for building VC included in the repo contain local paths. I've removed them from the repo and fixed `vc/Makefile` to regenerate them on the first `make` run based on the `CONFIGURE` file content.

### CODE REVIEW

**Comment by bcpierce00** [comment]
Thanks!  (Is there a similar issue with the other volumes of SF?)

**Comment by bravit** [comment]
> Is there a similar issue with the other volumes of SF?

I don't think so. The problem was with external dependencies to VST and/or CompCert.

**Comment by bcpierce00** [comment]
OK, merged.  Andrew, we should also fix the source repo.

**Comment by andrew-appel** [comment]
Thank you @bravit.  But these lines in Makefile.local are probably inappropriate; VST/compcert should not contain a working clightgen (nor the files that build it), because of CompCert licensing issues.
```
ifeq ($(CC_LOC),)
CC_LOC= $(VST_LOC)/compcert
endif
```

**Comment by bravit** [comment]
@andrew-appel, as far as I understand these lines are for locating generated files only, not for clightgen itself or the files that build it. I just tried to accomodate both suggested ways to use VST: with or without CompCert installed locally.

**Comment by andrew-appel** [comment]
That's a reasonable point; but still, for tutorial use (such as in this textbook), I want to keep things simple.

**Pull request merged**
